owner: aid-ly
repo: upptime

sites:
  - name: Aid-Ly
    url: https://aid-ly.org

status-website:
  cname: upptime.aid-ly.org
  logoUrl: https://aid-ly.org/android-chrome-512x512.png
  favicon: https://aid-ly.org/favicon.ico
  name: Upptime | aid-ly
  robotsText: "User-agent: * \nAllow: /"
  introTitle: "[**aid-ly.org**](https://aid-ly.org)'s upptime status page powered by [Upptime](https://github.com/upptime/upptime)."
  introMessage: This page contains **real-time** data from [aid-ly.org](https://aid-ly.org)'s websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
